apiVersion: apps/v1
kind: Deployment
metadata:
  name: diameter-gateway-haproxy
  namespace: brc-ns-cnpcrf-cnpcrf
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: diameter-gateway-haproxy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: diameter-gateway-haproxy
    spec:
      containers:
      - image: whiteregistry.brcws.tcloud.ar/oracle/occnp/ha-proxy:2.3.9-alpine
        imagePullPolicy: IfNotPresent
        name: haproxy
        ports:
        - containerPort: 3868
          protocol: TCP
        - containerPort: 8404
          name: stat
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/local/etc/haproxy/haproxy.cfg
          name: haproxy-config
          subPath: haproxy.cfg
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      setHostnameAsFQDN: false
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: haproxy-config
        name: haproxy-config
