apiVersion: v1
kind: Service
metadata:
  name: diameter-haproxy-service
  namespace: brc-ns-cnpcrf-cnpcrf
  resourceVersion: "100914187"
  uid: 54351c80-bd01-4133-847e-dc22b15867c9
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: diameter
    port: 3868
    protocol: TCP
    targetPort: 3868
  selector:
    io.kompose.service: brc-cnp-cnpcrf-oc-diam-gateway
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}